/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.modules.SignIn.view;

/**
 *
 * @author 1º DAW
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signusers = new javax.swing.ButtonGroup();
        addusername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        signin = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        btnadmin = new javax.swing.JButton();
        btnclient = new javax.swing.JButton();
        btnruser = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        addpass = new javax.swing.JTextField();
        statuslog = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(addusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 151, -1));

        jLabel1.setText("User name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        signin.setText("Sign In");
        getContentPane().add(signin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        exit.setText("Exit");
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        btnadmin.setText("Admin");
        signusers.add(btnadmin);
        getContentPane().add(btnadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 44, -1, -1));

        btnclient.setText("Client");
        signusers.add(btnclient);
        getContentPane().add(btnclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 44, -1, -1));

        btnruser.setText("Registered user");
        signusers.add(btnruser);
        getContentPane().add(btnruser, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 44, -1, -1));

        jLabel3.setText("Iniciar sesión como:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 11, 157, -1));
        getContentPane().add(addpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 151, -1));
        getContentPane().add(statuslog, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 390, 12));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/modules/SignIn/view/img/login.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 90, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField addpass;
    public static javax.swing.JTextField addusername;
    public static javax.swing.JButton btnadmin;
    public static javax.swing.JButton btnclient;
    public static javax.swing.JButton btnruser;
    public static javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JButton signin;
    private javax.swing.ButtonGroup signusers;
    public static javax.swing.JLabel statuslog;
    // End of variables declaration//GEN-END:variables
}
