/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.modules.users.admin.view;

import app.classes.singleton_global;
import static app.classes.singleton_global.Green;
import app.modules.users.admin.model.BLL.BLL_admin;
import static app.modules.users.admin.view.adminmanage_view.statusnewadmin;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author 1º DAW
 */
public class adminnew_view extends javax.swing.JFrame {
/*    Calendar fnac;
    int dia, mes, anyo;
    private FileNameExtensionFilter filter = new FileNameExtensionFilter
        ("Archivo de imagen","jpg","png","gif");
    String rutaimagen;*/
    /**
     * Creates new form newadmin_view
     */
    public adminnew_view() {
        initComponents();
     //   rutaimagen="";
     //   confpage();
        
    }

  /*  private void confpage(){
        this.setLocationRelativeTo(null);
        this.setSize(590,541);
        this.setResizable(false);
    }*/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblname = new javax.swing.JLabel();
        addname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addsurname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        adddni = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addmobile = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        addemail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        adddatebirthday = new com.toedter.calendar.JDateChooser();
        dni_validate = new javax.swing.JLabel();
        name_validate = new javax.swing.JLabel();
        surname_validate = new javax.swing.JLabel();
        mobile_validate = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        addnameuser = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        addpassword = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        addavatar = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        add_status = new javax.swing.JComboBox<>();
        email_validate = new javax.swing.JLabel();
        avatar_validate = new javax.swing.JLabel();
        state_validate = new javax.swing.JLabel();
        avataradd = new javax.swing.JButton();
        createadmin = new javax.swing.JButton();
        canceladmin = new javax.swing.JButton();
        titlecreateedit = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlblcreate = new javax.swing.JLabel();
        nameuser_validate = new javax.swing.JLabel();
        password_validate = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        addcontr = new com.toedter.calendar.JDateChooser();
        addsalary = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        addactivity = new javax.swing.JTextField();
        validateactivity = new javax.swing.JLabel();
        validatesalary = new javax.swing.JLabel();
        validatebirthday = new javax.swing.JLabel();
        validate_cont = new javax.swing.JLabel();
        createoredit = new javax.swing.JLabel();
        adddummies = new javax.swing.JButton();
        currency = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblname.setText("Nombre");
        getContentPane().add(jlblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 70, 20));

        addname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                addnameFocusLost(evt);
            }
        });
        addname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnameActionPerformed(evt);
            }
        });
        addname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addnameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addnameKeyTyped(evt);
            }
        });
        getContentPane().add(addname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 132, -1));

        jLabel2.setText("Apellidos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 70, 20));

        addsurname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                addsurnameFocusLost(evt);
            }
        });
        addsurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addsurnameActionPerformed(evt);
            }
        });
        addsurname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addsurnameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addsurnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addsurnameKeyTyped(evt);
            }
        });
        getContentPane().add(addsurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 132, -1));

        jLabel3.setText("DNI");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 70, 20));

        adddni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                adddniFocusLost(evt);
            }
        });
        adddni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adddniActionPerformed(evt);
            }
        });
        adddni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                adddniKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                adddniKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                adddniKeyTyped(evt);
            }
        });
        getContentPane().add(adddni, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 132, -1));

        jLabel4.setText("Teléfono");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 70, 20));

        addmobile.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                addmobileFocusLost(evt);
            }
        });
        addmobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmobileActionPerformed(evt);
            }
        });
        addmobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addmobileKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addmobileKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addmobileKeyTyped(evt);
            }
        });
        getContentPane().add(addmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 134, -1));

        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 70, 20));

        addemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                addemailFocusLost(evt);
            }
        });
        addemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addemailActionPerformed(evt);
            }
        });
        addemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addemailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addemailKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addemailKeyTyped(evt);
            }
        });
        getContentPane().add(addemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 134, -1));

        jLabel6.setText("F. nacimiento");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 80, 20));

        adddatebirthday.setToolTipText("");
        adddatebirthday.setDateFormatString("dd/MM/yyyy");
        adddatebirthday.setMaxSelectableDate(new java.util.Date(32503680084000L));
        adddatebirthday.setMinSelectableDate(new java.util.Date(-2208985677000L));
        getContentPane().add(adddatebirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 130, -1));
        getContentPane().add(dni_validate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 28, 20));
        getContentPane().add(name_validate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 28, 20));
        getContentPane().add(surname_validate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 28, 20));
        getContentPane().add(mobile_validate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 30, 20));

        jLabel12.setText("Usuario");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 60, 20));

        addnameuser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                addnameuserFocusLost(evt);
            }
        });
        addnameuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnameuserActionPerformed(evt);
            }
        });
        addnameuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addnameuserKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addnameuserKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addnameuserKeyTyped(evt);
            }
        });
        getContentPane().add(addnameuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 134, -1));

        jLabel13.setText("Contraseña");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 70, 20));

        addpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                addpasswordFocusLost(evt);
            }
        });
        addpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpasswordActionPerformed(evt);
            }
        });
        addpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addpasswordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addpasswordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addpasswordKeyTyped(evt);
            }
        });
        getContentPane().add(addpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 134, -1));

        jLabel14.setText("Avatar");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 70, 20));

        addavatar.setText("image.jpg");
        getContentPane().add(addavatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 91, 84));

        jLabel15.setText("Estado");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 60, 20));

        add_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Online", "Offline" }));
        getContentPane().add(add_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 134, -1));
        getContentPane().add(email_validate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 30, 20));
        getContentPane().add(avatar_validate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(state_validate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        avataradd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/modules/users/admin/view/img/addfile.png"))); // NOI18N
        avataradd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avataraddActionPerformed(evt);
            }
        });
        getContentPane().add(avataradd, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 39, 30));

        createadmin.setBackground(new java.awt.Color(255, 0, 153));
        createadmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/modules/users/admin/view/img/accept.png"))); // NOI18N
        createadmin.setToolTipText("Crear");
        createadmin.setBorder(null);
        createadmin.setContentAreaFilled(false);
        createadmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createadmin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        createadmin.setIconTextGap(-3);
        createadmin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(createadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 75, -1));

        canceladmin.setBackground(new java.awt.Color(255, 0, 153));
        canceladmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/modules/users/admin/view/img/cancel.png"))); // NOI18N
        canceladmin.setToolTipText("Descartar");
        canceladmin.setBorder(null);
        canceladmin.setContentAreaFilled(false);
        canceladmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        canceladmin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        canceladmin.setIconTextGap(-3);
        canceladmin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        canceladmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canceladminMouseClicked(evt);
            }
        });
        getContentPane().add(canceladmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 75, -1));

        titlecreateedit.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        titlecreateedit.setText("Crear un administrador");
        titlecreateedit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(titlecreateedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 11, 290, -1));

        jLabel7.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel7AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 42, 9));
        getContentPane().add(jlblcreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 489, 290, 20));
        getContentPane().add(nameuser_validate, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 28, 20));
        getContentPane().add(password_validate, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 28, 20));

        jLabel8.setText("F. contratación");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 80, 20));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 310, 384, 10));

        jLabel9.setText("Salario base");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 70, 20));

        addcontr.setDateFormatString("dd-MM-yyyy");
        addcontr.setMaxSelectableDate(new java.util.Date(32503680118000L));
        addcontr.setMinSelectableDate(new java.util.Date(-2208985643000L));
        getContentPane().add(addcontr, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 130, -1));

        addsalary.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                addsalaryFocusLost(evt);
            }
        });
        addsalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addsalaryActionPerformed(evt);
            }
        });
        addsalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addsalaryKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addsalaryKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addsalaryKeyTyped(evt);
            }
        });
        getContentPane().add(addsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 100, -1));

        jLabel10.setText("Actividad");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 80, 20));

        addactivity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                addactivityFocusLost(evt);
            }
        });
        addactivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addactivityActionPerformed(evt);
            }
        });
        addactivity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addactivityKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addactivityKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addactivityKeyTyped(evt);
            }
        });
        getContentPane().add(addactivity, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 128, -1));
        getContentPane().add(validateactivity, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 30, 20));
        getContentPane().add(validatesalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 30, 20));
        getContentPane().add(validatebirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 30, 20));
        getContentPane().add(validate_cont, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 30, 20));
        getContentPane().add(createoredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 40, 20));

        adddummies.setText("Add dummies");
        getContentPane().add(adddummies, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, -1, -1));

        currency.setText("€");
        getContentPane().add(currency, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 20, 20));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addmobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmobileActionPerformed
        // TODO add your handling code here:
     //   BLL_admin.MobileValidate();
    }//GEN-LAST:event_addmobileActionPerformed

    private void avataraddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avataraddActionPerformed
        // TODO add your handling code here:
   /*     JFileChooser dlg= new JFileChooser();
        dlg.setFileFilter(filter);
        int option = dlg.showOpenDialog(this);
        if(option==JFileChooser.APPROVE_OPTION){
            String filename = dlg.getSelectedFile().getPath();
            String fileurl = dlg.getSelectedFile().toString();
            addavatar.setText(fileurl);
        }*/
    }//GEN-LAST:event_avataraddActionPerformed
    
    private void jLabel7AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel7AncestorAdded
        // TODO add your handling code here:
   /*     this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                dispose();
                new adminmanage_view().setVisible(true);
            }
        });*/
    }//GEN-LAST:event_jLabel7AncestorAdded

    private void adddniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adddniActionPerformed
        // TODO add your handling code here: Validar DNI
  //      BLL_admin.DniValidate();
    }//GEN-LAST:event_adddniActionPerformed

    private void addnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnameActionPerformed
        // TODO add your handling code here: Validar nombre
 //       BLL_admin.NameValidate();
    }//GEN-LAST:event_addnameActionPerformed

    private void addnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addnameFocusLost
        // TODO add your handling code here:
  //      BLL_admin.NameValidate();
    }//GEN-LAST:event_addnameFocusLost

    private void addnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addnameKeyPressed
        // TODO add your handling code here:
  //      BLL_admin.NameValidate();
    }//GEN-LAST:event_addnameKeyPressed

    private void addnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addnameKeyReleased
        // TODO add your handling code here:
//        BLL_admin.NameValidate();
    }//GEN-LAST:event_addnameKeyReleased

    private void addnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addnameKeyTyped
        // TODO add your handling code here:
  //      BLL_admin.NameValidate();
    }//GEN-LAST:event_addnameKeyTyped

    private void addsurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addsurnameActionPerformed
        // TODO add your handling code here:
  //      BLL_admin.SurnameValidate();
    }//GEN-LAST:event_addsurnameActionPerformed

    private void addsurnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addsurnameFocusLost
        // TODO add your handling code here:
  //      BLL_admin.SurnameValidate();
    }//GEN-LAST:event_addsurnameFocusLost

    private void addsurnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addsurnameKeyPressed
        // TODO add your handling code here:
  //      BLL_admin.SurnameValidate();
    }//GEN-LAST:event_addsurnameKeyPressed

    private void addsurnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addsurnameKeyReleased
        // TODO add your handling code here:
  //      BLL_admin.SurnameValidate();
    }//GEN-LAST:event_addsurnameKeyReleased

    private void addsurnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addsurnameKeyTyped
        // TODO add your handling code here:
   //     BLL_admin.SurnameValidate();
    }//GEN-LAST:event_addsurnameKeyTyped

    private void addmobileFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addmobileFocusLost
        // TODO add your handling code here:
    //    BLL_admin.MobileValidate();
    }//GEN-LAST:event_addmobileFocusLost

    private void addmobileKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addmobileKeyPressed
        // TODO add your handling code here:
   //     BLL_admin.MobileValidate();
    }//GEN-LAST:event_addmobileKeyPressed

    private void addmobileKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addmobileKeyReleased
        // TODO add your handling code here:
   //     BLL_admin.MobileValidate();
    }//GEN-LAST:event_addmobileKeyReleased

    private void addmobileKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addmobileKeyTyped
        // TODO add your handling code here:
   //     BLL_admin.MobileValidate();
    }//GEN-LAST:event_addmobileKeyTyped

    private void addemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addemailActionPerformed
        // TODO add your handling code here:
   //     BLL_admin.EmailValidate();
    }//GEN-LAST:event_addemailActionPerformed

    private void addemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addemailFocusLost
        // TODO add your handling code here:
  //      BLL_admin.EmailValidate();
    }//GEN-LAST:event_addemailFocusLost

    private void addemailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addemailKeyPressed
        // TODO add your handling code here:
  //      BLL_admin.EmailValidate();
    }//GEN-LAST:event_addemailKeyPressed

    private void addemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addemailKeyReleased
        // TODO add your handling code here:
  //      BLL_admin.EmailValidate();
    }//GEN-LAST:event_addemailKeyReleased

    private void addemailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addemailKeyTyped
        // TODO add your handling code here:
  //      BLL_admin.EmailValidate();
    }//GEN-LAST:event_addemailKeyTyped

    private void addnameuserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addnameuserFocusLost
        // TODO add your handling code here:
 //       BLL_admin.UserNameValidate();
    }//GEN-LAST:event_addnameuserFocusLost

    private void addnameuserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addnameuserKeyPressed
        // TODO add your handling code here:
   //     BLL_admin.UserNameValidate();
    }//GEN-LAST:event_addnameuserKeyPressed

    private void addnameuserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addnameuserKeyReleased
        // TODO add your handling code here:
  //      BLL_admin.UserNameValidate();
    }//GEN-LAST:event_addnameuserKeyReleased

    private void addnameuserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addnameuserKeyTyped
        // TODO add your handling code here:
  //      BLL_admin.UserNameValidate();
    }//GEN-LAST:event_addnameuserKeyTyped

    private void addnameuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnameuserActionPerformed
        // TODO add your handling code here:
  //      BLL_admin.UserNameValidate();
    }//GEN-LAST:event_addnameuserActionPerformed

    private void addpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpasswordActionPerformed
        // TODO add your handling code here:
   //     BLL_admin.PasswordValidate();
    }//GEN-LAST:event_addpasswordActionPerformed

    private void addpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addpasswordFocusLost
        // TODO add your handling code here:
   //     BLL_admin.PasswordValidate();
    }//GEN-LAST:event_addpasswordFocusLost

    private void addpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addpasswordKeyPressed
        // TODO add your handling code here:
   //     BLL_admin.PasswordValidate();
    }//GEN-LAST:event_addpasswordKeyPressed

    private void addpasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addpasswordKeyReleased
        // TODO add your handling code here:
 //       BLL_admin.PasswordValidate();
    }//GEN-LAST:event_addpasswordKeyReleased

    private void addpasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addpasswordKeyTyped
        // TODO add your handling code here:
  //      BLL_admin.PasswordValidate();
    }//GEN-LAST:event_addpasswordKeyTyped

    private void adddniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adddniFocusLost
        // TODO add your handling code here:
  //      BLL_admin.DniValidate();
    }//GEN-LAST:event_adddniFocusLost

    private void adddniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adddniKeyPressed
        // TODO add your handling code here:
   //     BLL_admin.DniValidate();
    }//GEN-LAST:event_adddniKeyPressed

    private void adddniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adddniKeyReleased
        // TODO add your handling code here:
   //     BLL_admin.DniValidate();
    }//GEN-LAST:event_adddniKeyReleased

    private void adddniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adddniKeyTyped
        // TODO add your handling code here:
    //    BLL_admin.DniValidate();
    }//GEN-LAST:event_adddniKeyTyped

    private void canceladminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canceladminMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_canceladminMouseClicked

    private void addsalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addsalaryActionPerformed
        // TODO add your handling code here:
  //      BLL_admin.SalaryValidate();
    }//GEN-LAST:event_addsalaryActionPerformed

    private void addsalaryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addsalaryFocusLost
        // TODO add your handling code here:
  //      BLL_admin.SalaryValidate();
    }//GEN-LAST:event_addsalaryFocusLost

    private void addsalaryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addsalaryKeyPressed
        // TODO add your handling code here:
   //     BLL_admin.SalaryValidate();
    }//GEN-LAST:event_addsalaryKeyPressed

    private void addsalaryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addsalaryKeyReleased
        // TODO add your handling code here:
   //     BLL_admin.SalaryValidate();
    }//GEN-LAST:event_addsalaryKeyReleased

    private void addsalaryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addsalaryKeyTyped
        // TODO add your handling code here:
   //     BLL_admin.SalaryValidate();
    }//GEN-LAST:event_addsalaryKeyTyped

    private void addactivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addactivityActionPerformed
        // TODO add your handling code here:
   //     BLL_admin.ActivityValidate();
    }//GEN-LAST:event_addactivityActionPerformed

    private void addactivityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addactivityFocusLost
        // TODO add your handling code here:
   //     BLL_admin.ActivityValidate();
    }//GEN-LAST:event_addactivityFocusLost

    private void addactivityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addactivityKeyPressed
        // TODO add your handling code here:
    //    BLL_admin.ActivityValidate();
    }//GEN-LAST:event_addactivityKeyPressed

    private void addactivityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addactivityKeyReleased
        // TODO add your handling code here:
  //      BLL_admin.ActivityValidate();
    }//GEN-LAST:event_addactivityKeyReleased

    private void addactivityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addactivityKeyTyped
        // TODO add your handling code here:
   //     BLL_admin.ActivityValidate();
    }//GEN-LAST:event_addactivityKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            app.modules.users.admin.model.BLL.BLL_admin.crearAdminBBDD();
        } catch (SQLException ex) {
            Logger.getLogger(adminnew_view.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         *
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminnew_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminnew_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminnew_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminnew_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form *//*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminnew_view().setVisible(true);
            }
        });*/
    //}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> add_status;
    public static javax.swing.JTextField addactivity;
    public static javax.swing.JTextField addavatar;
    public static com.toedter.calendar.JDateChooser addcontr;
    public static com.toedter.calendar.JDateChooser adddatebirthday;
    public static javax.swing.JTextField adddni;
    public static javax.swing.JButton adddummies;
    public static javax.swing.JTextField addemail;
    public static javax.swing.JTextField addmobile;
    public static javax.swing.JTextField addname;
    public static javax.swing.JTextField addnameuser;
    public static javax.swing.JPasswordField addpassword;
    public static javax.swing.JTextField addsalary;
    public static javax.swing.JTextField addsurname;
    public static javax.swing.JLabel avatar_validate;
    public static javax.swing.JButton avataradd;
    public static javax.swing.JButton canceladmin;
    public static javax.swing.JButton createadmin;
    public static javax.swing.JLabel createoredit;
    public static javax.swing.JLabel currency;
    public static javax.swing.JLabel dni_validate;
    public static javax.swing.JLabel email_validate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel12;
    public static javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel14;
    public static javax.swing.JLabel jLabel15;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JLabel jlblcreate;
    public static javax.swing.JLabel jlblname;
    public static javax.swing.JLabel mobile_validate;
    public static javax.swing.JLabel name_validate;
    public static javax.swing.JLabel nameuser_validate;
    public static javax.swing.JLabel password_validate;
    public static javax.swing.JLabel state_validate;
    public static javax.swing.JLabel surname_validate;
    public static javax.swing.JLabel titlecreateedit;
    public static javax.swing.JLabel validate_cont;
    public static javax.swing.JLabel validateactivity;
    public static javax.swing.JLabel validatebirthday;
    public static javax.swing.JLabel validatesalary;
    // End of variables declaration//GEN-END:variables
}
