/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.modules.menu.view;

import app.classes.singleton_global;
import app.modules.config.view.config_view;
import app.modules.users.admin.view.adminmanage_view;
import app.utils.config_save;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
//import app.modules.users.model.BLL.lib_ficheros.*;
/**
 *
 * @author Lara
 */
public class main_view extends javax.swing.JFrame {

    /**
     * Creates new form main_view
     */
    public main_view() {
        initComponents();
        confpage();
        btnadmin_main.setText(singleton_global.translate.getProperty("admin"));
        btnclient_main.setText(singleton_global.translate.getProperty("client"));
        btnreguser_main.setText(singleton_global.translate.getProperty("registered_user"));
        btnconf_main.setText(singleton_global.translate.getProperty("config"));
    }
    private void confpage(){
        this.setSize(409,343);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnclient_main = new javax.swing.JButton();
        btnconf_main = new javax.swing.JButton();
        btnadmin_main = new javax.swing.JButton();
        btnreguser_main = new javax.swing.JButton();
        background_main = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de usuarios");
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/modules/menu/view/img/user_manage.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 30, 173, 181);

        jLabel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(365, 0, 42, 11);

        btnclient_main.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/modules/menu/view/img/client.png"))); // NOI18N
        btnclient_main.setText("Cliente");
        btnclient_main.setToolTipText("Conviértete en cliente y consigue descuentos en tus compras");
        btnclient_main.setActionCommand("");
        btnclient_main.setBorder(null);
        btnclient_main.setContentAreaFilled(false);
        btnclient_main.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnclient_main.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnclient_main.setIconTextGap(-1);
        btnclient_main.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnclient_main);
        btnclient_main.setBounds(30, 120, 90, 80);

        btnconf_main.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/modules/menu/view/img/config.png"))); // NOI18N
        btnconf_main.setText("Configuración");
        btnconf_main.setToolTipText("Modifica la aplicación a tu gusto");
        btnconf_main.setActionCommand("");
        btnconf_main.setBorder(null);
        btnconf_main.setContentAreaFilled(false);
        btnconf_main.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnconf_main.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnconf_main.setIconTextGap(-3);
        btnconf_main.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/app/modules/menu/view/img/config_press.png"))); // NOI18N
        btnconf_main.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/app/modules/menu/view/img/config_press.png"))); // NOI18N
        btnconf_main.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnconf_main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconf_mainActionPerformed(evt);
            }
        });
        getContentPane().add(btnconf_main);
        btnconf_main.setBounds(310, 230, 90, 80);

        btnadmin_main.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/modules/menu/view/img/admin.png"))); // NOI18N
        btnadmin_main.setText("Administrador");
        btnadmin_main.setToolTipText("Usuarios con permiso de administración");
        btnadmin_main.setActionCommand("");
        btnadmin_main.setBorder(null);
        btnadmin_main.setContentAreaFilled(false);
        btnadmin_main.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnadmin_main.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnadmin_main.setIconTextGap(-1);
        btnadmin_main.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/app/modules/menu/view/img/admin_press.png"))); // NOI18N
        btnadmin_main.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/app/modules/menu/view/img/admin_press.png"))); // NOI18N
        btnadmin_main.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnadmin_main.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnadmin_mainMouseEntered(evt);
            }
        });
        btnadmin_main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadmin_mainActionPerformed(evt);
            }
        });
        getContentPane().add(btnadmin_main);
        btnadmin_main.setBounds(30, 21, 90, 80);

        btnreguser_main.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/modules/menu/view/img/registered.png"))); // NOI18N
        btnreguser_main.setText("Registrado");
        btnreguser_main.setToolTipText("Regístrate para conseguir puntos con tu actividad y aumentar tu nivel de karma");
        btnreguser_main.setActionCommand("");
        btnreguser_main.setBorder(null);
        btnreguser_main.setContentAreaFilled(false);
        btnreguser_main.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnreguser_main.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnreguser_main.setIconTextGap(-1);
        btnreguser_main.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnreguser_main);
        btnreguser_main.setBounds(30, 220, 90, 80);

        background_main.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/modules/menu/view/img/background_main.png"))); // NOI18N
        getContentPane().add(background_main);
        background_main.setBounds(-10, -6, 420, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jLabel2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel2AncestorAdded
        // TODO add your handling code here:
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
		addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                JOptionPane.showMessageDialog(null,"Saliendo de la aplicación");
                config_save.GenerateJsonautoconf();
                
                dispose();
                System.exit(0);
            }
        });
    }//GEN-LAST:event_jLabel2AncestorAdded
    
    private void btnadmin_mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadmin_mainActionPerformed
        // TODO add your handling code here:
        //new adminmain_view().setVisible(true);
        new adminmanage_view().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnadmin_mainActionPerformed

    private void btnconf_mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconf_mainActionPerformed
        // TODO add your handling code here:
        new config_view().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnconf_mainActionPerformed

    private void btnadmin_mainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnadmin_mainMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnadmin_mainMouseEntered
    
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         *
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form *
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_view().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background_main;
    public static javax.swing.JButton btnadmin_main;
    public static javax.swing.JButton btnclient_main;
    public static javax.swing.JButton btnconf_main;
    public static javax.swing.JButton btnreguser_main;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
