/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.modules.menu.view;

import app.modules.config.view.config_view;
import app.modules.users.view.adminmain_view;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;

/**
 *
 * @author 1º DAW
 */
public class main_view extends javax.swing.JFrame {

    /**
     * Creates new form main_view
     */
    public main_view() {
        initComponents();
        confpage();
    }
    private void confpage(){
        this.setSize(409,343);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        admin_main = new javax.swing.JButton();
        conf_main = new javax.swing.JButton();
        admin_main2 = new javax.swing.JButton();
        admin_main3 = new javax.swing.JButton();
        background_main = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de usuarios");
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/modules/menu/view/img/user_manage.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 30, 173, 181);

        jLabel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(365, 0, 42, 11);

        admin_main.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/modules/menu/view/img/client.png"))); // NOI18N
        admin_main.setText("Cliente");
        admin_main.setToolTipText("Conviértete en cliente y consigue descuentos en tus compras");
        admin_main.setActionCommand("");
        admin_main.setBorder(null);
        admin_main.setContentAreaFilled(false);
        admin_main.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        admin_main.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        admin_main.setIconTextGap(-1);
        admin_main.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(admin_main);
        admin_main.setBounds(30, 120, 90, 80);

        conf_main.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/modules/menu/view/img/config.png"))); // NOI18N
        conf_main.setText("Configuración");
        conf_main.setToolTipText("Modifica la aplicación a tu gusto");
        conf_main.setActionCommand("");
        conf_main.setBorder(null);
        conf_main.setContentAreaFilled(false);
        conf_main.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        conf_main.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        conf_main.setIconTextGap(-3);
        conf_main.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/app/modules/menu/view/img/config_press.png"))); // NOI18N
        conf_main.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/app/modules/menu/view/img/config_press.png"))); // NOI18N
        conf_main.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        conf_main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conf_mainActionPerformed(evt);
            }
        });
        getContentPane().add(conf_main);
        conf_main.setBounds(310, 230, 90, 80);

        admin_main2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/modules/menu/view/img/admin.png"))); // NOI18N
        admin_main2.setText("Administrador");
        admin_main2.setToolTipText("Usuarios con permiso de administración");
        admin_main2.setActionCommand("");
        admin_main2.setBorder(null);
        admin_main2.setContentAreaFilled(false);
        admin_main2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        admin_main2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        admin_main2.setIconTextGap(-1);
        admin_main2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/app/modules/menu/view/img/admin_press.png"))); // NOI18N
        admin_main2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/app/modules/menu/view/img/admin_press.png"))); // NOI18N
        admin_main2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        admin_main2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                admin_main2MouseEntered(evt);
            }
        });
        admin_main2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_main2ActionPerformed(evt);
            }
        });
        getContentPane().add(admin_main2);
        admin_main2.setBounds(30, 21, 90, 80);

        admin_main3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/modules/menu/view/img/registered.png"))); // NOI18N
        admin_main3.setText("Registrado");
        admin_main3.setToolTipText("Regístrate para conseguir puntos con tu actividad y aumentar tu nivel de karma");
        admin_main3.setActionCommand("");
        admin_main3.setBorder(null);
        admin_main3.setContentAreaFilled(false);
        admin_main3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        admin_main3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        admin_main3.setIconTextGap(-1);
        admin_main3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(admin_main3);
        admin_main3.setBounds(30, 220, 90, 80);

        background_main.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/modules/menu/view/img/background_main.png"))); // NOI18N
        getContentPane().add(background_main);
        background_main.setBounds(-10, -6, 420, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel2AncestorAdded
        // TODO add your handling code here:
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
		addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                JOptionPane.showMessageDialog(null,"Saliendo de la aplicación");
                dispose();
                System.exit(0);
            }
        });
    }//GEN-LAST:event_jLabel2AncestorAdded

    private void admin_main2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_main2ActionPerformed
        // TODO add your handling code here:
        new adminmain_view().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_admin_main2ActionPerformed

    private void conf_mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conf_mainActionPerformed
        // TODO add your handling code here:
        new config_view().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_conf_mainActionPerformed

    private void admin_main2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin_main2MouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_admin_main2MouseEntered
    
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         *
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form *
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_view().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton admin_main;
    public static javax.swing.JButton admin_main2;
    public static javax.swing.JButton admin_main3;
    private javax.swing.JLabel background_main;
    public static javax.swing.JButton conf_main;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
