/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.modules.users.client.view;

/**
 *
 * @author Lara
 */
public class clientnew_view extends javax.swing.JFrame {
    public clientnew_view() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblname = new javax.swing.JLabel();
        addname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addsurname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        adddni = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addmobile = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        addemail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        adddatebirthday = new com.toedter.calendar.JDateChooser();
        dni_validate = new javax.swing.JLabel();
        name_validate = new javax.swing.JLabel();
        surname_validate = new javax.swing.JLabel();
        mobile_validate = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        addnameuser = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        addpassword = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        addavatar = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        addpremium = new javax.swing.JComboBox<>();
        email_validate = new javax.swing.JLabel();
        avatar_validate = new javax.swing.JLabel();
        state_validate = new javax.swing.JLabel();
        avataradd = new javax.swing.JButton();
        createclient = new javax.swing.JButton();
        cancelclient = new javax.swing.JButton();
        titlecreateedit = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlblcreate = new javax.swing.JLabel();
        nameuser_validate = new javax.swing.JLabel();
        password_validate = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        addshopping = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        adddesc = new javax.swing.JTextField();
        validateactivity = new javax.swing.JLabel();
        validatesalary = new javax.swing.JLabel();
        validatebirthday = new javax.swing.JLabel();
        validate_cont = new javax.swing.JLabel();
        createoredit = new javax.swing.JLabel();
        adddummies = new javax.swing.JButton();
        addreg = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        add_status = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        addtype = new javax.swing.JTextField();
        addyearsservice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblname.setText("Nombre");
        getContentPane().add(jlblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 70, 20));

        addname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                addnameFocusLost(evt);
            }
        });
        addname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnameActionPerformed(evt);
            }
        });
        addname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addnameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addnameKeyTyped(evt);
            }
        });
        getContentPane().add(addname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 132, -1));

        jLabel2.setText("Apellidos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 70, 20));

        addsurname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                addsurnameFocusLost(evt);
            }
        });
        addsurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addsurnameActionPerformed(evt);
            }
        });
        addsurname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addsurnameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addsurnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addsurnameKeyTyped(evt);
            }
        });
        getContentPane().add(addsurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 132, -1));

        jLabel3.setText("DNI");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 80, 20));

        adddni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                adddniFocusLost(evt);
            }
        });
        adddni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adddniActionPerformed(evt);
            }
        });
        adddni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                adddniKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                adddniKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                adddniKeyTyped(evt);
            }
        });
        getContentPane().add(adddni, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 132, -1));

        jLabel4.setText("Teléfono");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 70, 20));

        addmobile.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                addmobileFocusLost(evt);
            }
        });
        addmobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmobileActionPerformed(evt);
            }
        });
        addmobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addmobileKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addmobileKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addmobileKeyTyped(evt);
            }
        });
        getContentPane().add(addmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 134, -1));

        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 70, 20));

        addemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                addemailFocusLost(evt);
            }
        });
        addemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addemailActionPerformed(evt);
            }
        });
        addemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addemailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addemailKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addemailKeyTyped(evt);
            }
        });
        getContentPane().add(addemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 134, -1));

        jLabel6.setText("F. nacimiento");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 80, 20));

        adddatebirthday.setToolTipText("");
        adddatebirthday.setDateFormatString("dd-MM-yyyy");
        adddatebirthday.setMaxSelectableDate(new java.util.Date(32503680084000L));
        adddatebirthday.setMinSelectableDate(new java.util.Date(-2208985677000L));
        getContentPane().add(adddatebirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 130, -1));
        getContentPane().add(dni_validate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 28, 20));
        getContentPane().add(name_validate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 28, 20));
        getContentPane().add(surname_validate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 28, 20));
        getContentPane().add(mobile_validate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 30, 20));

        jLabel12.setText("Usuario");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 60, 20));

        addnameuser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                addnameuserFocusLost(evt);
            }
        });
        addnameuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnameuserActionPerformed(evt);
            }
        });
        addnameuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addnameuserKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addnameuserKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addnameuserKeyTyped(evt);
            }
        });
        getContentPane().add(addnameuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 134, -1));

        jLabel13.setText("Contraseña");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 70, 20));

        addpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                addpasswordFocusLost(evt);
            }
        });
        addpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpasswordActionPerformed(evt);
            }
        });
        addpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addpasswordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addpasswordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addpasswordKeyTyped(evt);
            }
        });
        getContentPane().add(addpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 134, -1));

        jLabel14.setText("Avatar");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 70, 20));

        addavatar.setText("image.jpg");
        getContentPane().add(addavatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 91, 84));

        jLabel15.setText("Estado");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 60, 20));

        addpremium.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Premium", "Standard" }));
        getContentPane().add(addpremium, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 130, -1));
        getContentPane().add(email_validate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 30, 20));
        getContentPane().add(avatar_validate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(state_validate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        avataradd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/modules/users/admin/view/img/addfile.png"))); // NOI18N
        getContentPane().add(avataradd, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 39, 30));

        createclient.setBackground(new java.awt.Color(255, 0, 153));
        createclient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/modules/users/admin/view/img/accept.png"))); // NOI18N
        createclient.setToolTipText("Crear");
        createclient.setBorder(null);
        createclient.setContentAreaFilled(false);
        createclient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createclient.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        createclient.setIconTextGap(-3);
        createclient.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(createclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 75, -1));

        cancelclient.setBackground(new java.awt.Color(255, 0, 153));
        cancelclient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/modules/users/admin/view/img/cancel.png"))); // NOI18N
        cancelclient.setToolTipText("Descartar");
        cancelclient.setBorder(null);
        cancelclient.setContentAreaFilled(false);
        cancelclient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelclient.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancelclient.setIconTextGap(-3);
        cancelclient.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cancelclient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelclientMouseClicked(evt);
            }
        });
        getContentPane().add(cancelclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, 75, -1));

        titlecreateedit.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        titlecreateedit.setText("Crear un cliente");
        titlecreateedit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(titlecreateedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 11, 260, -1));

        jLabel7.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel7AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 42, 9));
        getContentPane().add(jlblcreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 290, 20));
        getContentPane().add(nameuser_validate, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 28, 20));
        getContentPane().add(password_validate, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 28, 20));

        jLabel8.setText("F. registro");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 80, 20));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 310, 384, 10));

        jLabel9.setText("Compras");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 70, 20));

        addshopping.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                addshoppingFocusLost(evt);
            }
        });
        addshopping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addshoppingActionPerformed(evt);
            }
        });
        addshopping.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addshoppingKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addshoppingKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addshoppingKeyTyped(evt);
            }
        });
        getContentPane().add(addshopping, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 120, -1));

        jLabel10.setText("Años de servicio");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 80, 20));

        adddesc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                adddescFocusLost(evt);
            }
        });
        adddesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adddescActionPerformed(evt);
            }
        });
        adddesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                adddescKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                adddescKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                adddescKeyTyped(evt);
            }
        });
        getContentPane().add(adddesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 120, -1));
        getContentPane().add(validateactivity, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 30, 20));
        getContentPane().add(validatesalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 30, 20));
        getContentPane().add(validatebirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 30, 20));
        getContentPane().add(validate_cont, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 30, 20));
        getContentPane().add(createoredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 40, 20));

        adddummies.setText("Add dummies");
        getContentPane().add(adddummies, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, -1, -1));

        addreg.setDateFormatString("dd-MM-yyyy");
        addreg.setMaxSelectableDate(new java.util.Date(32503680118000L));
        addreg.setMinSelectableDate(new java.util.Date(-2208985643000L));
        getContentPane().add(addreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 130, -1));

        jLabel1.setText("Descuento");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 70, 20));

        jLabel11.setText("Premium");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 90, 20));

        add_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Online", "Offline" }));
        getContentPane().add(add_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 134, -1));

        jLabel16.setText("Tipo");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 70, 20));
        getContentPane().add(addtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 120, -1));
        getContentPane().add(addyearsservice, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addmobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmobileActionPerformed
    
    }//GEN-LAST:event_addmobileActionPerformed
    
    private void jLabel7AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel7AncestorAdded
        // TODO add your handling code here:
   /*     this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                dispose();
                new adminmanage_view().setVisible(true);
            }
        });*/
    }//GEN-LAST:event_jLabel7AncestorAdded

    private void adddniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adddniActionPerformed
        // TODO add your handling code here: Validar DNI
  //      BLL_admin.DniValidate();
    }//GEN-LAST:event_adddniActionPerformed

    private void addnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnameActionPerformed
        // TODO add your handling code here: Validar nombre
 //       BLL_admin.NameValidate();
    }//GEN-LAST:event_addnameActionPerformed

    private void addnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addnameFocusLost
        // TODO add your handling code here:
  //      BLL_admin.NameValidate();
    }//GEN-LAST:event_addnameFocusLost

    private void addnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addnameKeyPressed
        // TODO add your handling code here:
  //      BLL_admin.NameValidate();
    }//GEN-LAST:event_addnameKeyPressed

    private void addnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addnameKeyReleased
        // TODO add your handling code here:
//        BLL_admin.NameValidate();
    }//GEN-LAST:event_addnameKeyReleased

    private void addnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addnameKeyTyped
        // TODO add your handling code here:
  //      BLL_admin.NameValidate();
    }//GEN-LAST:event_addnameKeyTyped

    private void addsurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addsurnameActionPerformed
        // TODO add your handling code here:
  //      BLL_admin.SurnameValidate();
    }//GEN-LAST:event_addsurnameActionPerformed

    private void addsurnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addsurnameFocusLost
        // TODO add your handling code here:
  //      BLL_admin.SurnameValidate();
    }//GEN-LAST:event_addsurnameFocusLost

    private void addsurnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addsurnameKeyPressed
        // TODO add your handling code here:
  //      BLL_admin.SurnameValidate();
    }//GEN-LAST:event_addsurnameKeyPressed

    private void addsurnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addsurnameKeyReleased
        // TODO add your handling code here:
  //      BLL_admin.SurnameValidate();
    }//GEN-LAST:event_addsurnameKeyReleased

    private void addsurnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addsurnameKeyTyped
        // TODO add your handling code here:
   //     BLL_admin.SurnameValidate();
    }//GEN-LAST:event_addsurnameKeyTyped

    private void addmobileFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addmobileFocusLost
        // TODO add your handling code here:
    //    BLL_admin.MobileValidate();
    }//GEN-LAST:event_addmobileFocusLost

    private void addmobileKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addmobileKeyPressed
        // TODO add your handling code here:
   //     BLL_admin.MobileValidate();
    }//GEN-LAST:event_addmobileKeyPressed

    private void addmobileKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addmobileKeyReleased
        // TODO add your handling code here:
   //     BLL_admin.MobileValidate();
    }//GEN-LAST:event_addmobileKeyReleased

    private void addmobileKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addmobileKeyTyped
        // TODO add your handling code here:
   //     BLL_admin.MobileValidate();
    }//GEN-LAST:event_addmobileKeyTyped

    private void addemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addemailActionPerformed
        // TODO add your handling code here:
   //     BLL_admin.EmailValidate();
    }//GEN-LAST:event_addemailActionPerformed

    private void addemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addemailFocusLost
        // TODO add your handling code here:
  //      BLL_admin.EmailValidate();
    }//GEN-LAST:event_addemailFocusLost

    private void addemailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addemailKeyPressed
        // TODO add your handling code here:
  //      BLL_admin.EmailValidate();
    }//GEN-LAST:event_addemailKeyPressed

    private void addemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addemailKeyReleased
        // TODO add your handling code here:
  //      BLL_admin.EmailValidate();
    }//GEN-LAST:event_addemailKeyReleased

    private void addemailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addemailKeyTyped
        // TODO add your handling code here:
  //      BLL_admin.EmailValidate();
    }//GEN-LAST:event_addemailKeyTyped

    private void addnameuserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addnameuserFocusLost
        // TODO add your handling code here:
 //       BLL_admin.UserNameValidate();
    }//GEN-LAST:event_addnameuserFocusLost

    private void addnameuserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addnameuserKeyPressed
        // TODO add your handling code here:
   //     BLL_admin.UserNameValidate();
    }//GEN-LAST:event_addnameuserKeyPressed

    private void addnameuserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addnameuserKeyReleased
        // TODO add your handling code here:
  //      BLL_admin.UserNameValidate();
    }//GEN-LAST:event_addnameuserKeyReleased

    private void addnameuserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addnameuserKeyTyped
        // TODO add your handling code here:
  //      BLL_admin.UserNameValidate();
    }//GEN-LAST:event_addnameuserKeyTyped

    private void addnameuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnameuserActionPerformed
        // TODO add your handling code here:
  //      BLL_admin.UserNameValidate();
    }//GEN-LAST:event_addnameuserActionPerformed

    private void addpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpasswordActionPerformed
        // TODO add your handling code here:
   //     BLL_admin.PasswordValidate();
    }//GEN-LAST:event_addpasswordActionPerformed

    private void addpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addpasswordFocusLost
        // TODO add your handling code here:
   //     BLL_admin.PasswordValidate();
    }//GEN-LAST:event_addpasswordFocusLost

    private void addpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addpasswordKeyPressed
        // TODO add your handling code here:
   //     BLL_admin.PasswordValidate();
    }//GEN-LAST:event_addpasswordKeyPressed

    private void addpasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addpasswordKeyReleased
        // TODO add your handling code here:
 //       BLL_admin.PasswordValidate();
    }//GEN-LAST:event_addpasswordKeyReleased

    private void addpasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addpasswordKeyTyped
        // TODO add your handling code here:
  //      BLL_admin.PasswordValidate();
    }//GEN-LAST:event_addpasswordKeyTyped

    private void adddniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adddniFocusLost
        // TODO add your handling code here:
  //      BLL_admin.DniValidate();
    }//GEN-LAST:event_adddniFocusLost

    private void adddniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adddniKeyPressed
        // TODO add your handling code here:
   //     BLL_admin.DniValidate();
    }//GEN-LAST:event_adddniKeyPressed

    private void adddniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adddniKeyReleased
        // TODO add your handling code here:
   //     BLL_admin.DniValidate();
    }//GEN-LAST:event_adddniKeyReleased

    private void adddniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adddniKeyTyped
        // TODO add your handling code here:
    //    BLL_admin.DniValidate();
    }//GEN-LAST:event_adddniKeyTyped

    private void cancelclientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelclientMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cancelclientMouseClicked

    private void addshoppingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addshoppingActionPerformed
        // TODO add your handling code here:
  //      BLL_admin.SalaryValidate();
    }//GEN-LAST:event_addshoppingActionPerformed

    private void addshoppingFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addshoppingFocusLost
        // TODO add your handling code here:
  //      BLL_admin.SalaryValidate();
    }//GEN-LAST:event_addshoppingFocusLost

    private void addshoppingKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addshoppingKeyPressed
        // TODO add your handling code here:
   //     BLL_admin.SalaryValidate();
    }//GEN-LAST:event_addshoppingKeyPressed

    private void addshoppingKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addshoppingKeyReleased
        // TODO add your handling code here:
   //     BLL_admin.SalaryValidate();
    }//GEN-LAST:event_addshoppingKeyReleased

    private void addshoppingKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addshoppingKeyTyped
        // TODO add your handling code here:
   //     BLL_admin.SalaryValidate();
    }//GEN-LAST:event_addshoppingKeyTyped

    private void adddescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adddescActionPerformed
        // TODO add your handling code here:
   //     BLL_admin.ActivityValidate();
    }//GEN-LAST:event_adddescActionPerformed

    private void adddescFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adddescFocusLost
        // TODO add your handling code here:
   //     BLL_admin.ActivityValidate();
    }//GEN-LAST:event_adddescFocusLost

    private void adddescKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adddescKeyPressed
        // TODO add your handling code here:
    //    BLL_admin.ActivityValidate();
    }//GEN-LAST:event_adddescKeyPressed

    private void adddescKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adddescKeyReleased
        // TODO add your handling code here:
  //      BLL_admin.ActivityValidate();
    }//GEN-LAST:event_adddescKeyReleased

    private void adddescKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adddescKeyTyped
        // TODO add your handling code here:
   //     BLL_admin.ActivityValidate();
    }//GEN-LAST:event_adddescKeyTyped

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         *
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminnew_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminnew_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminnew_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminnew_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form *//*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminnew_view().setVisible(true);
            }
        });*/
    //}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> add_status;
    public static javax.swing.JTextField addavatar;
    public static com.toedter.calendar.JDateChooser adddatebirthday;
    public static javax.swing.JTextField adddesc;
    public static javax.swing.JTextField adddni;
    public static javax.swing.JButton adddummies;
    public static javax.swing.JTextField addemail;
    public static javax.swing.JTextField addmobile;
    public static javax.swing.JTextField addname;
    public static javax.swing.JTextField addnameuser;
    public static javax.swing.JPasswordField addpassword;
    public static javax.swing.JComboBox<String> addpremium;
    public static com.toedter.calendar.JDateChooser addreg;
    public static javax.swing.JTextField addshopping;
    public static javax.swing.JTextField addsurname;
    public static javax.swing.JTextField addtype;
    public static javax.swing.JTextField addyearsservice;
    public static javax.swing.JLabel avatar_validate;
    public static javax.swing.JButton avataradd;
    public static javax.swing.JButton cancelclient;
    public static javax.swing.JButton createclient;
    public static javax.swing.JLabel createoredit;
    public static javax.swing.JLabel dni_validate;
    public static javax.swing.JLabel email_validate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    public static javax.swing.JLabel jLabel12;
    public static javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel14;
    public static javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JLabel jlblcreate;
    public static javax.swing.JLabel jlblname;
    public static javax.swing.JLabel mobile_validate;
    public static javax.swing.JLabel name_validate;
    public static javax.swing.JLabel nameuser_validate;
    public static javax.swing.JLabel password_validate;
    public static javax.swing.JLabel state_validate;
    public static javax.swing.JLabel surname_validate;
    public static javax.swing.JLabel titlecreateedit;
    public static javax.swing.JLabel validate_cont;
    public static javax.swing.JLabel validateactivity;
    public static javax.swing.JLabel validatebirthday;
    public static javax.swing.JLabel validatesalary;
    // End of variables declaration//GEN-END:variables
}
