/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.modules.users.client.view;

/**
 *
 * @author Lara
 */
public class clientnew_view extends javax.swing.JFrame {
    public clientnew_view() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblname = new javax.swing.JLabel();
        caddname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        caddsurname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        adddnic = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        caddmobile = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        caddemail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cadddatebirthday = new com.toedter.calendar.JDateChooser();
        dni_validate = new javax.swing.JLabel();
        name_validate = new javax.swing.JLabel();
        surname_validate = new javax.swing.JLabel();
        mobile_validate = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        caddnameuser = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        caddpassword = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        caddavatar = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        caddpremium = new javax.swing.JComboBox<>();
        email_validate = new javax.swing.JLabel();
        avatar_validate = new javax.swing.JLabel();
        state_validate = new javax.swing.JLabel();
        avataradd = new javax.swing.JButton();
        createclient = new javax.swing.JButton();
        cancelclient = new javax.swing.JButton();
        titlecreateedit = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlblcreate = new javax.swing.JLabel();
        nameuser_validate = new javax.swing.JLabel();
        password_validate = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        caddshopping = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cadddesc = new javax.swing.JTextField();
        validateactivity = new javax.swing.JLabel();
        validatesalary = new javax.swing.JLabel();
        validatebirthday = new javax.swing.JLabel();
        validate_cont = new javax.swing.JLabel();
        createoredit = new javax.swing.JLabel();
        adddummies = new javax.swing.JButton();
        caddreg = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cadd_status = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        caddtype = new javax.swing.JTextField();
        caddyearsservice = new javax.swing.JTextField();
        logoutclient = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblname.setText("Nombre");
        getContentPane().add(jlblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 70, 20));
        getContentPane().add(caddname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 132, -1));

        jLabel2.setText("Apellidos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 70, 20));
        getContentPane().add(caddsurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 132, -1));

        jLabel3.setText("DNI");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 80, 20));
        getContentPane().add(adddnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 132, -1));

        jLabel4.setText("Teléfono");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 70, 20));
        getContentPane().add(caddmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 134, -1));

        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 70, 20));
        getContentPane().add(caddemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 134, -1));

        jLabel6.setText("F. nacimiento");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 80, 20));

        cadddatebirthday.setToolTipText("");
        cadddatebirthday.setDateFormatString("dd-MM-yyyy");
        cadddatebirthday.setMaxSelectableDate(new java.util.Date(32503680084000L));
        cadddatebirthday.setMinSelectableDate(new java.util.Date(-2208985677000L));
        getContentPane().add(cadddatebirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 130, -1));
        getContentPane().add(dni_validate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 28, 20));
        getContentPane().add(name_validate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 28, 20));
        getContentPane().add(surname_validate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 28, 20));
        getContentPane().add(mobile_validate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 30, 20));

        jLabel12.setText("Usuario");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 60, 20));
        getContentPane().add(caddnameuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 134, -1));

        jLabel13.setText("Contraseña");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 70, 20));
        getContentPane().add(caddpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 134, -1));

        jLabel14.setText("Avatar");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 70, 20));

        caddavatar.setText("image.jpg");
        getContentPane().add(caddavatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 91, 84));

        jLabel15.setText("Estado");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 60, 20));

        caddpremium.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Premium", "Standard" }));
        getContentPane().add(caddpremium, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 130, -1));
        getContentPane().add(email_validate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 30, 20));
        getContentPane().add(avatar_validate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(state_validate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        avataradd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/modules/users/admin/view/img/addfile.png"))); // NOI18N
        getContentPane().add(avataradd, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 39, 30));

        createclient.setBackground(new java.awt.Color(255, 0, 153));
        createclient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/modules/users/admin/view/img/accept.png"))); // NOI18N
        createclient.setToolTipText("Crear");
        createclient.setBorder(null);
        createclient.setContentAreaFilled(false);
        createclient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createclient.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        createclient.setIconTextGap(-3);
        createclient.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(createclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 75, -1));

        cancelclient.setBackground(new java.awt.Color(255, 0, 153));
        cancelclient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/modules/users/admin/view/img/cancel.png"))); // NOI18N
        cancelclient.setToolTipText("Descartar");
        cancelclient.setBorder(null);
        cancelclient.setContentAreaFilled(false);
        cancelclient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelclient.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancelclient.setIconTextGap(-3);
        cancelclient.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(cancelclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, 75, -1));

        titlecreateedit.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        titlecreateedit.setText("Crear un cliente");
        titlecreateedit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(titlecreateedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 11, 260, -1));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 42, 9));
        getContentPane().add(jlblcreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 290, 20));
        getContentPane().add(nameuser_validate, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 28, 20));
        getContentPane().add(password_validate, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 28, 20));

        jLabel8.setText("F. registro");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 80, 20));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 310, 384, 10));

        jLabel9.setText("Compras");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 70, 20));
        getContentPane().add(caddshopping, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 120, -1));

        jLabel10.setText("Años de servicio");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 80, 20));
        getContentPane().add(cadddesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 120, -1));
        getContentPane().add(validateactivity, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 30, 20));
        getContentPane().add(validatesalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 30, 20));
        getContentPane().add(validatebirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 30, 20));
        getContentPane().add(validate_cont, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 30, 20));
        getContentPane().add(createoredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 40, 20));

        adddummies.setText("Add dummies");
        getContentPane().add(adddummies, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        caddreg.setDateFormatString("dd-MM-yyyy");
        caddreg.setMaxSelectableDate(new java.util.Date(32503680118000L));
        caddreg.setMinSelectableDate(new java.util.Date(-2208985643000L));
        getContentPane().add(caddreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 130, -1));

        jLabel1.setText("Descuento");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 70, 20));

        jLabel11.setText("Premium");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 90, 20));

        cadd_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Online", "Offline" }));
        getContentPane().add(cadd_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 134, -1));

        jLabel16.setText("Tipo");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 70, 20));
        getContentPane().add(caddtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 120, -1));
        getContentPane().add(caddyearsservice, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 130, -1));

        logoutclient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/modules/menu/view/img/door-48.png"))); // NOI18N
        logoutclient.setToolTipText("Cerrar sesión");
        logoutclient.setBorder(null);
        logoutclient.setContentAreaFilled(false);
        logoutclient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutclient.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logoutclient.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/app/modules/menu/view/img/door2-48.png"))); // NOI18N
        logoutclient.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/app/modules/menu/view/img/door2-48.png"))); // NOI18N
        logoutclient.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(logoutclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField adddnic;
    public static javax.swing.JButton adddummies;
    public static javax.swing.JLabel avatar_validate;
    public static javax.swing.JButton avataradd;
    public static javax.swing.JComboBox<String> cadd_status;
    public static javax.swing.JTextField caddavatar;
    public static com.toedter.calendar.JDateChooser cadddatebirthday;
    public static javax.swing.JTextField cadddesc;
    public static javax.swing.JTextField caddemail;
    public static javax.swing.JTextField caddmobile;
    public static javax.swing.JTextField caddname;
    public static javax.swing.JTextField caddnameuser;
    public static javax.swing.JPasswordField caddpassword;
    public static javax.swing.JComboBox<String> caddpremium;
    public static com.toedter.calendar.JDateChooser caddreg;
    public static javax.swing.JTextField caddshopping;
    public static javax.swing.JTextField caddsurname;
    public static javax.swing.JTextField caddtype;
    public static javax.swing.JTextField caddyearsservice;
    public static javax.swing.JButton cancelclient;
    public static javax.swing.JButton createclient;
    public static javax.swing.JLabel createoredit;
    public static javax.swing.JLabel dni_validate;
    public static javax.swing.JLabel email_validate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    public static javax.swing.JLabel jLabel12;
    public static javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel14;
    public static javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JLabel jlblcreate;
    public static javax.swing.JLabel jlblname;
    public static javax.swing.JButton logoutclient;
    public static javax.swing.JLabel mobile_validate;
    public static javax.swing.JLabel name_validate;
    public static javax.swing.JLabel nameuser_validate;
    public static javax.swing.JLabel password_validate;
    public static javax.swing.JLabel state_validate;
    public static javax.swing.JLabel surname_validate;
    public static javax.swing.JLabel titlecreateedit;
    public static javax.swing.JLabel validate_cont;
    public static javax.swing.JLabel validateactivity;
    public static javax.swing.JLabel validatebirthday;
    public static javax.swing.JLabel validatesalary;
    // End of variables declaration//GEN-END:variables
}
